version: '3.6'

services:

  db:
    image: postgis/postgis:12-master
    env_file:
      - wiredcraft_test_backend.env
    volumes:
      - db_volume:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - wiredcraft_test_backend.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_volume:
