version: '3.7'
services:
  database:
    image: mongo:4
    container_name: test-mongo-db
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - test-mongo-data:/data/db

volumes:
  test-mongo-data:
