version: '3'

services:
  redis:
    image: redis:6.2.4
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./.docker/redis/data/:/data

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  jaeger:
    image: jaegertracing/all-in-one:1.23.0
    ports:
      - 6832:6832/udp
      - 16686:16686

  rabbitmq:
    image: rabbitmq:3.8.18-beta.1-management
    ports:
      - 5672:5672
      - 15672:15672
    # 如果需要rabbitmq持久化，则打开注释，会保存数据，重启镜像不会丢失
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq
      - ./.docker/rabbitmq/:/var/log/rabbitmq
