name: integration_test

on:
  pull_request:
    branches:    
      - master

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Building the project
      run: npm run build 
    - name: Run docker compose
      run: docker-compose -f mongo.docker-compose.yml up -d
    - name: Run `npm test`
      run: npm test
      env:
        CI: true
